# Generated by Django 4.0 on 2021-12-26 04:24

from django.db import migrations

# create dummy data
def create_data(apps, schema_editor):
    Patient = apps.get_model('patients', 'Patient')
    Patient(first_name="John", last_name="Doe", email="johndoe@email.com", phone="4169999999", address="John Doe's Address", description="Patient 000").save()

class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
